"""Suggested state keys for later ADK session integration."""

TARGET_BASE_URL = "target.base_url"
TARGET_OUTPUT_DIR = "target.output_dir"
TARGET_MODE = "target.mode"

BROWSER_SESSION_NAME = "browser.session_name"
BROWSER_HEADED = "browser.headed"
BROWSER_PERSISTENT = "browser.persistent"
BROWSER_CURRENT_URL = "browser.current_url"
BROWSER_CURRENT_TITLE = "browser.current_title"
BROWSER_STORAGE_STATE_PATH = "browser.storage_state_path"

CRAWL_START_URL = "crawl.start_url"
CRAWL_VISITED_PATHS = "crawl.visited_paths"
CRAWL_PENDING_PATHS = "crawl.pending_paths"
CRAWL_DISCOVERED_LINKS = "crawl.discovered_links"
CRAWL_DISCOVERED_FORMS = "crawl.discovered_forms"
CRAWL_REQUIRES_LOGIN = "crawl.requires_login"
CRAWL_PHASE = "crawl.phase"
CRAWL_ROUTE_PARENTS = "crawl.route_parents"
CRAWL_SKIPPED_ROUTES = "crawl.skipped_routes"
CRAWL_ERROR_ATTEMPTS = "crawl.error_attempts"

WORKING_CURRENT_PAGE = "working.current_page"
WORKING_RECENT_FEEDBACK = "working.recent_feedback"
WORKING_CONTEXT_PACK = "working.context_pack"

AUTH_CREDENTIALS_FILE = "auth.credentials_file"
AUTH_USERNAME = "auth.username"
AUTH_PASSWORD_SOURCE = "auth.password_source"
AUTH_LOGGED_IN = "auth.logged_in"

OUTPUT_GENERATED_FILES = "output.generated_files"
OUTPUT_ROUTE_MANIFEST_PATH = "output.route_manifest_path"
OUTPUT_FORMAT = "output.format"
OUTPUT_VALIDATION_SUMMARY = "output.validation_summary"

POLICY_ALLOW_ADMIN_SUBMIT = "policy.allow_admin_submit"
POLICY_ALLOW_DESTRUCTIVE_CLICKS = "policy.allow_destructive_clicks"
POLICY_ALLOW_FILE_WRITE = "policy.allow_file_write"

LONG_TERM_FINAL_GOAL = "long_term.final_goal"
LONG_TERM_TARGET_APP = "long_term.target_app"
LONG_TERM_CREDENTIAL_REFS = "long_term.credential_refs"
LONG_TERM_STORAGE_STATE_PATHS = "long_term.storage_state_paths"
LONG_TERM_KNOWN_SAFE_EXCLUSIONS = "long_term.known_safe_exclusions"
LONG_TERM_BLOCKED_ACTIONS = "long_term.blocked_actions"
LONG_TERM_AVOIDED_ERROR_PATHS = "long_term.avoided_error_paths"
